spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
            issuer-uri: http://localhost:8080/realms/rentify-cloud
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/rentify-cloud
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: rentify-gateway
            client-secret: 1pV2Lp73ezQQKUvFvRgJuTfGPjI9yAof
            scope: openid

  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
        ssl:
          useInsecureTrustManager: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
        add-to-simple-url-handler-mapping: true
      routes:
        - id: registerBusinessAccount
          uri: lb://AUTHORIZATION-SERVICE
          predicates:
            - Path=/api/auth/business-account/register
eureka:
  client:
    service-url.defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
        preferIpAddress: true

server:
  port: 8082